Truncate Table Orders;

Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),1,1000,100,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),2,1002,103,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),2,1013,103,'Cancelled');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),3,1026,107,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),3,1026,107,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),4,1141,109,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),5,1041,106,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),5,1048,106,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),6,1210,104,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),7,1052,110,'Cancelled');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),8,1210,104,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),9,1007,108,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),10,1039,104,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),10,1026,107,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),11,1053,100,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),8,1049,107,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),8,1102,110,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),12,1050,108,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),13,1004,105,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),13,1015,105,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),14,1044,101,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),14,1208,101,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),15,1065,103,'Completed');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),16,1204,109,'Submitted');
Insert into Orders(Order_On,C_Id,P_Id,S_Id,O_Status) values(GETUTCDATE(),17,1040,105,'Submitted');