Truncate Table dbo.Stores;
Insert into Stores(Store_Name,Website,Address,Created_On) values('Flipkarts','www.Flipkarts.com/example',null,GetUTCDATE());
Insert into Stores(Store_Name,Website,Address,Created_On) values('Bengaluru',null,'230,Whitefield Main Road',GetUTCDATE());
Insert into Stores(Store_Name,Website,Address,Created_On) values('Mumbai',null,'467, Bandra EAST','2022-12-31');
Insert into Stores(Store_Name,Website,Address,Created_On) values('New Delhi',null,'120, Ashok Nagar West Delhi','2022-11-23');
Insert into Stores(Store_Name,Website,Address,Created_On) values('Kolkata',null,'289, A.J.C Bose Road','2023-01-15');
Insert into Stores(Store_Name,Website,Address,Created_On) values('Hyderabad',null,'330, High Tech City','2022-12-31');
Insert into Stores(Store_Name,Website,Address,Created_On) values('Amazon','www.amazon.com/example',null,'2023-01-02');
Insert into Stores(Store_Name,Website,Address,Created_On) values('London',null,'356,Park Mall Road','2023-02-22');
Insert into Stores(Store_Name,Website,Address,Created_On) values('Madrid',null,'223 Plaza MAyor','2023-02-20');
Insert into Stores(Store_Name,Website,Address,Created_On) values('Manchester',null,'540 Old Traford','2023-02-23');
